### ISSUE TITLE
Add openSUSE release names?

### ISSUE THREAD

**Issue by dcermak** [rpm-software-management/fedora-distro-aliases#15]
We'd like to have a collection of the current openSUSE releases for packit (see https://github.com/packit/packit/pull/2343). Would it be possible to add them to this module? It would render the name a little more invalid than it is at the moment already as it includes EPEL as well.

We unfortunately cannot query bodhy, but we can parse the contents of https://get.opensuse.org/api/v0/distributions.json for this.

cc @lachmanfrantisek @rxbryan

**Comment by FrostyX** [comment]
Hello @dcermak,
thank you for the RFE.

We discussed this with @lachmanfrantisek and @xsuchy one or two weeks ago.

- My main concern is that we don't want any external dependencies. We initially used [bodhi-client](https://pypi.org/project/bodhi-client/) and dropping the dependency was the first thing people requested after the project was announced. Other than that, I had no objections to adding support for openSUSE here
- @xsuchy thinks it would be better if those were separate projects. Mainly because the whole code has ~100 lines and the majority of it is the communication with Bodhi and Fedora-specific stuff. Not much that can be reused for openSUSE.

The consensus was that it would be great if openSUSE created a new project called `opensuse-distro-aliases` and kept the same public interface, so that all the usage examples mentioned in the README
https://github.com/rpm-software-management/fedora-distro-aliases?tab=readme-ov-file#usage
would work for openSUSE as well (except the import would be different)

We could then link each other's projects in the READMEs, etc. And in case other distributions did the same, we could create a `distro-aliases` metapackage that would install them all. And/or provide some shared code for validating the public interface, caching, etc.

What do you think @dcermak?

**Comment by dcermak** [comment]
I have created a PoC: https://github.com/dcermak/opensuse-distro-aliases

It's very light on dependencies (currently it only requires `requests`) and I've tried to expose a comparable interface as this project.

**Comment by lachmanfrantisek** [comment]
@dcermak,  thanks Dan!

**Comment by dcermak** [comment]
@FrostyX @xsuchy would it be possible to transfer the opensuse-distro-aliases project into the `rpm-software-management` management? I'd prefer it not being only in my personal namespace

**Comment by FrostyX** [comment]
I think it is a good idea, +1
Not sure if me or @xsuchy can do the transfer because we are only members of the group, not owners. I certainly can try, and if we find a permission error, I find us some group owner. Please ping me on Matrix and we can figure out the transfer.

**Comment by xsuchy** [comment]
I will ask @jan-kolarik

**Comment by FrostyX** [comment]
Already migrated https://github.com/rpm-software-management/opensuse-distro-aliases
